king_ad/urls.py


from django.urls import path
from king_ad import views

urlpatterns = [
    path(r'list',views.index,name="table_index"),
    path(r'<app_name>/<table_name>/',views.display_table_objs,name="table_objs"),
    path(r'<app_name>/<table_name>/<id>/change/', views.table_objs_change, name="table_obj_change"),
    path(r'<app_name>/<table_name>/<id>/delete/', views.table_obj_delete, name="obj_delete"),
    path(r'<app_name>/<table_name>/add/',views.table_obj_add,name="table_obj_add"),
]

redmine2/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from redmine2 import views as redmine
from user import views as user
from django.views.static import serve
from django.conf import settings
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'static/<path>.*', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='upload'),
    path(r'king_ad/', include('king_ad.urls')),
    path(r'login/', user.login, name='login'),
    path(r'logout/', user.logout),
    path(r'', redmine.index, name='index'),
    path(r'<int:id>/change/', views.project_edit),
    path(r'<int:id>/', views.project_show),
    path(r'project/', include('project.urls')),
    path(r'auth/user/', user.user_obj, name='auth_user'),
    path(r'role/', user.role_obj, name='role'),
    path(r'role/add/', user.role_add, name='user_add'),
    path(r'role/<int:id>/change/', user.role_permission),
    path(r'personal/', user.personal, ),
    path(r'active/api/', user.active),
    path(r'auth/user/add/', user.user_add, name='auth_user_add'),
    path(r'auth/user/<int:id>/change/', user.user_edit, name='auth_user_change'),
    path(r'department/', user.depertment, name='department_user'),
    path(r'department/add/', user.department_add, name='department_add'),
    path(r'department/admin/', user.department_admin),
    path(r'department/<int:id>/change/', user.department_edit, name='department_edit'),
    # path(r'echo/', redmine.echo),
    path(r'400/', redmine.error_400),
    path(r'403/', redmine.error_403),
    path(r'404/', redmine.error_404),
    path(r'500/', redmine.error_500),
    path(r'503/', redmine.error_503), ]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = redmine.error_404
handler500 = redmine.error_500

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Permission,Group
# Create your models here.

class Role(models.Model):
    name = models.CharField(max_length=30,unique=True)
    permission = models.ManyToManyField(Permission)
    active = models.BooleanField(default=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "角色"
        verbose_name_plural = "角色"

class Department(models.Model):
    '''部门'''
    department_name = models.CharField(max_length=30, unique=True, verbose_name='名称')
    # active = models.BooleanField(default=True)
    # spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.department_name

    class Meta:
        verbose_name = "部门"
        verbose_name_plural = "部门"

class User(AbstractUser):
    phone = models.CharField(unique=True,max_length=20)
    head = models.ImageField(upload_to="image/user/%Y/%m/%d/",default="image/user/mo.jpg")
    gender_choice = (
        (0, "男"),
        (1, "女"),
    )
    gender = models.SmallIntegerField(choices=gender_choice,default=0)
    entry_time = models.DateField(null=True, blank=True)
    duty = models.CharField(max_length=20, null=True, blank=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE, null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    first_type = models.CharField(max_length=100, null=True, blank=True)
    two_type = models.CharField(max_length=100, null=True, blank=True)
    three_type = models.CharField(max_length=100, null=True, blank=True)
    four_type = models.CharField(max_length=100, null=True, blank=True)
    role = models.ForeignKey(Role,on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.first_name

    class Meta(AbstractUser.Meta):
        unique_together = ('email',)

class SessionUser(models.Model):
    session = models.CharField(max_length=100,unique=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)


class Csrf(models.Model):
    session = models.CharField(max_length=100, unique=True)
    csrf = models.CharField(max_length=100)

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block container %}
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
{#    <div class="preloader">#}
{#        <svg class="circular" viewBox="25 25 50 50">#}
{#            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>#}
{#        </svg>#}
{#    </div>#}
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper">
        <div class="login-register" style="padding: 11% 0">
            <div class="login-box">
                <div class="card-body">

                    <form class="form-horizontal" id="loginform" action="/login/" method="POST">
                        {% csrf_token %}
                        <div class="form-group " style="margin-bottom: 40px">
                            <img src="{% static 'assets/images/logo.png' %}" style="display: block;margin: 0 auto">
                        </div>
                        <div class="form-group ">
                            <input class="form-control" type="text" required="" placeholder="企业邮箱/手机号码" name="username">
                        </div>
                        <div class="form-group">
                            <input class="form-control" type="password" required="" placeholder="密码" name="password">
                        </div>
                        <div class="form-group row" style="margin-bottom: -10px;margin-top: -10px">
                            <div class="col-md-12 font-14">
                                <a href="javascript:void(0)" id="to-recover" class="pull-right" style="color:#028ee1">忘记密码？</a>
                            </div>
                        </div>
                        {% if login_error %}
                        <p style="color: #f33155"><i class="mdi mdi-alert-circle"></i>{{ login_error }}</p>
                        {% endif %}
                        <div class="form-group text-center m-t-20">
                            <button class="btn btn-info btn-block text-uppercase waves-effect waves-light" type="submit"
                                    style="padding: 10px 12px;">登陆
                            </button>
                        </div>
                        <div class="form-group m-b-0">
                            <div class="col-sm-12 text-center">
                                <div style="color: #028ee1">注册账号说明</div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/personal.html
{% extends 'index.html' %}
{% load tags %}
{% load static %}
{% block extra-css %}
    <style>
        .upload_pic {
            display: block;
            width: 100px;
            height: 100px;
            position: absolute;
            left: 0;
            top: 0;
            opacity: 0;
            border-radius: 5px;
        }

        .round_icon {
            width: 100px;
            height: 100px;
            display: flex;
            border-radius: 50%;
            background-color: #CCCCCC;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }
    </style>
{% endblock %}
{% block wrapper %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="panel-title" style="padding: 1rem 30px">用户创建</h3>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body" style="padding:3.2rem;">
                        <form class="form-horizontal" method="POST" style="margin-bottom: 0"
                              enctype="multipart/form-data" onsubmit="return pas()">
                            {% csrf_token %}
                            {{ errors }}
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group row">
                                            <label class="control-label col-md-2">用户头像</label>
                                            <div class="col-md-10" onsubmit="return pas()">
                                                <div class="round_icon" id="oDiv">
                                                    <input type="file" name="head" id="id_head"
                                                           class="form-control upload_pic">
                                                    {% if use %}
                                                        <img src="/media/{{ use.head }}" alt=""
                                                             style="width: 100%;height: 100%">
                                                    {% else %}
                                                        <img src="/media/image/user/mo.jpg" alt=""
                                                             style="width: 100%;height: 100%">
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group row">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>用户名</label>
                                            {{ user_forms.username }}
                                            <small class="form-control-feedback text-danger">{{ errors.userbame.0 }}</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>密码</label>
                                            <input type="password" name="password" maxlength="128"
                                                   id="id_password" onchange="passwo(this)">
                                            <small class="form-control-feedback">
                                                密码须由大、小写字母及数字组合而成，不能使用特殊字符，长度不得少于8个字符
                                            </small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>再次输入</label>
                                            <input type="password" maxlength="128"
                                                   id="id_password1" onchange="one(this)">
                                            <small class="form-control-feedback">
                                            </small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>手机号码</label>
                                            {{ user_forms.phone }}
                                            <small class="form-control-feedback text-danger">{{ errors.phone.0 }}</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>邮箱</label>
                                            {{ user_forms.email }}
                                            <small class="form-control-feedback text-danger">{{ errors.email.0 }}</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" class="btn btn-success">保存
                                    </button>
                                    <button type="button" class="btn btn-inverse"
                                            onclick="window.location.href='{% url "index" %}'">
                                        返回
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function one(obj) {
            if ($(obj).val() != $('#id_password').val()) {
                $(obj).parent().addClass('has-danger');
                $(obj).next().text('两次密码输入不一致，请重新输入');
            } else {
                $(obj).parent().removeClass('has-danger');
                $(obj).next().text('');
            }
        }

        function passwo(obj) {
            reg = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,10}/;
            pass = $(obj).val();
            if (pass) {
                if (!reg.test(pass)) {
                    $('#id_password').parent().addClass('has-danger');
                } else {
                    $('#id_password').parent().removeClass('has-danger');
                    $('#id_password').attr('required', '');
                    $('#id_password1').attr('required', '');
                }
            } else {
                $('#id_password').removeAttr('required', '');
                $('#id_password1').removeAttr('required', '');
            }
        }

        $('input').addClass('form-control');
        $('select').addClass('form-control');
        $('#id_head').addClass('upload_pic');
        $('#id_entry_time').attr('type', 'date');
        timeto($('input[name="entry_time"]'));
        $('#id_head').on('change', function () {
            image(this)
        });
        $('#id_first_name').attr('pattern', '[\u4e00-\u9fa5]');
        $('#id_phone').attr('pattern', '0?(13|14|15|18)[0-9]{9}');
        if ($('#id_first_name').val()) {
            $('#id_password').removeAttr('required');
            $('#id_password1').removeAttr('required');
        }
        $('#oDiv>a').remove();

        function imageLoaded(obj, src) {
            var img = new Image();
            if (src === undefined) {
                src = '';
            }
            img.onload = function () {
                obj.src = src;
            };
            img.src = src;
        }

        function image(obj) {
            var files = obj.files;

            var img = new Image();
            var render = new FileReader();
            render.readAsDataURL(files[0]);
            render.onloadstart = function () {
//				alert("start")
            };
            render.onload = function () {
                img.src = this.result;
                img.style.height = "100%";
                img.style.width = "100%";
                $(obj).prevAll('img').remove();
                $(obj).nextAll('img').remove();
                $(obj).after(img);
            };
            render.onloadend = function () {
//				alert("end");
            }
        }

        function timeto(obj) {
            if (obj.attr('value')) {
                var time = obj.attr('value');
                var ti = time.split("/");
                var a = ti.join("-");
                obj.attr('value', a);
            }
        }

        function pas() {
            if ($('#id_password').val()) {
                if ($('#id_password1').val() != $('#id_password').val()) {
                    alert("两次输入密码不相同！");
                    return false
                }
                else {
                    return true;
                }
            } else {
                return true;
            }
        }
    </script>
{% endblock %}

templates/user_change.html
{% extends 'index.html' %}
{% load tags %}
{% load static %}
{% block extra-css %}
    <style>
        .upload_pic {
            display: block;
            width: 100px;
            height: 100px;
            position: absolute;
            left: 0;
            top: 0;
            opacity: 0;
            border-radius: 5px;
        }

        .round_icon {
            width: 100px;
            height: 100px;
            display: flex;
            border-radius: 50%;
            background-color: #CCCCCC;
            align-items: center;
            justify-content: center;
            overflow: hidden;
        }

        li {
            list-style: none;
        }

        .errorlist {
            margin: 0;
        }
    </style>
{% endblock %}
{% block wrapper %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">用户</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
                <li class="breadcrumb-item"><a href="{% url 'auth_user' %}"></a>员工</li>
                {% if use %}
                    <li class="breadcrumb-item">编辑员工</li>
                {% else %}
                    <li class="breadcrumb-item">新建员工</li>
                {% endif %}

            </ol>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body" style="padding:3.2rem;">
                        <form class="form-horizontal" method="POST"
                              enctype="multipart/form-data" onsubmit="passwo()" style="margin-bottom: 0">
                            {% csrf_token %}
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="form-group row">
                                            <label class="control-label col-md-2">用户头像</label>
                                            <div class="col-md-10">
                                                <div class="round_icon" id="oDiv">
                                                    <input type="file" name="head" id="id_head"
                                                           class="form-control upload_pic">
                                                    {% if use %}
                                                        <img src="/media/{{ use.head }}" alt=""
                                                             style="width: 100%;height: 100%">
                                                    {% else %}
                                                        <img src="/media/image/user/mo.jpg" alt=""
                                                             style="width: 100%;height: 100%">
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="form-group row">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>中文名</label>
                                            {{ user_forms.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>英文名</label>
                                            {{ user_forms.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>性别</label>
                                            {{ user_forms.gender }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>入职时间</label>
                                            {{ user_forms.entry_time }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>部门</label>
                                            {{ user_forms.department }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>职位</label>
                                            {{ user_forms.duty }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>密码</label>
                                            <input type="password" name="password" maxlength="128" required=""
                                                   id="id_password" onchange="passwo()">
                                            <small class="form-control-feedback"> 密码须由大、小写字母及数字组合而成，不能使用特殊字符，长度不得少于8个字符
                                            </small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>手机号码</label>
                                            {{ user_forms.phone }}
                                            <small class="form-control-feedback text-danger">{{ errors.phone.0 }}</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>邮箱</label>
                                            {{ user_forms.email }}
                                            <small class="form-control-feedback text-danger">{{ errors.email.0 }}</small>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" class="btn btn-success">保存
                                    </button>
                                    <button type="button" class="btn btn-inverse"
                                            onclick="window.location.href='{% url "auth_user" %}'">
                                        返回
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        laydate.render({
            elem: '#id_entry_time'
            , type: 'date'
        });

        function passwo() {
            upform();
            reg = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,10}/;
            pass = $('#id_password').val();
            if (!reg.test(pass)) {
                $('#id_password').parent().addClass('has-danger');
                return false;
            } else {
                $('#id_password').parent().removeClass('has-danger');
                return true;
            }
        }

        $('select').children('option[value=""]').text("请选择");
        $('input[name="first_name"]').attr('required', '');
        $('input[name="last_name"]').attr('required', '');
        if ('{{ use }}') {
            $('input[type="password"]').removeAttr('required');
            $('input[name="user_permission"]').on('change', function () {
                $.ajax({
                    url: "/permission/api/",
                    type: "POST",
                    data: {
                        "user": '{{ use.id }}',
                        "id": $(this).val(),
                        "type": $(this).is(":checked"),
                    },
                    success: function (data) {
                    }
                });
            })
        }

        $('input').addClass('form-control');
        $('select').addClass('form-control');
        $('#id_head').addClass('upload_pic');
        timeto($('input[name="entry_time"]'));
        $('#id_head').on('change', function () {
            image(this)
        });
        if ($('#id_first_name').val()) {
            $('#id_password').removeAttr('required');
            $('#id_password1').removeAttr('required');
        }
        $('#oDiv>a').remove();

        function imageLoaded(obj, src) {
            var img = new Image();
            if (src === undefined) {
                src = '';
            }
            img.onload = function () {
                obj.src = src;
            };
            img.src = src;
        }

        function image(obj) {
            var files = obj.files;

            var img = new Image();
            var render = new FileReader();
            render.readAsDataURL(files[0]);
            render.onloadstart = function () {
//				alert("start")
            };
            render.onload = function () {
                img.src = this.result;
                img.style.height = "100%";
                img.style.width = "100%";
                $(obj).prevAll('img').remove();
                $(obj).nextAll('img').remove();
                $(obj).after(img);
            };
            render.onloadend = function () {
//				alert("end");
            }
        }

        function timeto(obj) {
            if (obj.attr('value')) {
                var time = obj.attr('value');
                var ti = time.split("/");
                var a = ti.join("-");
                obj.attr('value', a);
            }
        }
    </script>
{% endblock %}