king_ad/urls.py


from django.urls import path
from king_ad import views

urlpatterns = [
    path(r'list',views.index,name="table_index"),
    path(r'<app_name>/<table_name>/',views.display_table_objs,name="table_objs"),
    path(r'<app_name>/<table_name>/<id>/change/', views.table_objs_change, name="table_obj_change"),
    path(r'<app_name>/<table_name>/<id>/delete/', views.table_obj_delete, name="obj_delete"),
    path(r'<app_name>/<table_name>/add/',views.table_obj_add,name="table_obj_add"),
]

redmine2/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from redmine2 import views as redmine
from user import views as user
from django.views.static import serve
from django.conf import settings
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'static/<path>.*', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='upload'),
    path(r'king_ad/', include('king_ad.urls')),
    path(r'login/', user.login, name='login'),
    path(r'logout/', user.logout),
    path(r'', redmine.index, name='index'),
    path(r'<int:id>/change/', views.project_edit),
    path(r'<int:id>/', views.project_show),
    path(r'project/', include('project.urls')),
    path(r'auth/user/', user.user_obj, name='auth_user'),
    path(r'role/', user.role_obj, name='role'),
    path(r'role/add/', user.role_add, name='user_add'),
    path(r'role/<int:id>/change/', user.role_permission),
    path(r'personal/', user.personal, ),
    path(r'active/api/', user.active),
    path(r'auth/user/add/', user.user_add, name='auth_user_add'),
    path(r'auth/user/<int:id>/change/', user.user_edit, name='auth_user_change'),
    path(r'department/', user.depertment, name='department_user'),
    path(r'department/add/', user.department_add, name='department_add'),
    path(r'department/admin/', user.department_admin),
    path(r'department/<int:id>/change/', user.department_edit, name='department_edit'),
    # path(r'echo/', redmine.echo),
    path(r'400/', redmine.error_400),
    path(r'403/', redmine.error_403),
    path(r'404/', redmine.error_404),
    path(r'500/', redmine.error_500),
    path(r'503/', redmine.error_503), ]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = redmine.error_404
handler500 = redmine.error_500

king_ad/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Permission,Group
# Create your models here.

class Role(models.Model):
    name = models.CharField(max_length=30,unique=True)
    permission = models.ManyToManyField(Permission)
    active = models.BooleanField(default=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "角色"
        verbose_name_plural = "角色"

class Department(models.Model):
    '''部门'''
    department_name = models.CharField(max_length=30, unique=True, verbose_name='名称')
    # active = models.BooleanField(default=True)
    # spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.department_name

    class Meta:
        verbose_name = "部门"
        verbose_name_plural = "部门"

class User(AbstractUser):
    phone = models.CharField(unique=True,max_length=20)
    head = models.ImageField(upload_to="image/user/%Y/%m/%d/",default="image/user/mo.jpg")
    gender_choice = (
        (0, "男"),
        (1, "女"),
    )
    gender = models.SmallIntegerField(choices=gender_choice,default=0)
    entry_time = models.DateField(null=True, blank=True)
    duty = models.CharField(max_length=20, null=True, blank=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE, null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    first_type = models.CharField(max_length=100, null=True, blank=True)
    two_type = models.CharField(max_length=100, null=True, blank=True)
    three_type = models.CharField(max_length=100, null=True, blank=True)
    four_type = models.CharField(max_length=100, null=True, blank=True)
    role = models.ForeignKey(Role,on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.first_name

    class Meta(AbstractUser.Meta):
        unique_together = ('email',)

class SessionUser(models.Model):
    session = models.CharField(max_length=100,unique=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)


class Csrf(models.Model):
    session = models.CharField(max_length=100, unique=True)
    csrf = models.CharField(max_length=100)

king_ad/forms.py

from django.forms import forms,ModelForm


def create_model_form(request,admin_class):

    def __new__(cls,*args,**kwargs):
        for field_name,field_obj in cls.base_fields.items():
            field_obj.widget.attrs['class'] = 'form_contral'
        return ModelForm.__new__(cls)
    class Meta:
        model = admin_class.model
        fields = "__all__"

    attrs = {'Meta':Meta}
    _model_form_class = type("DynamicModelForm",(ModelForm,),{'Meta':Meta})
    setattr(_model_form_class,'__new__',__new__)

    return _model_form_class



king_ad/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from king_ad.utils import table_filter,table_sort,table_search
from king_ad import king_ad
from king_ad.forms import create_model_form
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from project import models as project
from user import models as us


# Create your views here.
def index_obj(request,app_name,table_name):
    admin_class = king_ad.enabled_admins[app_name][table_name]
    object_list, filter_condtions = table_filter(request, admin_class)
    object_list = table_search(request, admin_class, object_list)
    object_list, orderby_key = table_sort(request, admin_class, object_list)
    return admin_class, object_list, filter_condtions, orderby_key

def obj(request,app_name,table_name,ids=None,department=0):
    admin_class = king_ad.enabled_admins[app_name][table_name]
    object_list, filter_condtions = table_filter(request, admin_class)
    if ids:
        object_list = object_list.filter(id__in=ids)
    if department != 0:
        object_list = object_list.filter(department_id=department)
    object_list = table_search(request, admin_class, object_list)
    object_list, orderby_key = table_sort(request, admin_class, object_list)
    paginator = Paginator(object_list, admin_class.list_per_page)
    page = request.GET.get('page')
    try:
        query_sets = paginator.page(page)
    except PageNotAnInteger:
        query_sets = paginator.page(1)
    except EmptyPage:
        query_sets = paginator.page(paginator.num_pages)
    return admin_class,query_sets,filter_condtions,orderby_key

def index(request):
    return render(request, "king_ad/table_index.html",{'table_list':king_ad.enabled_admins})

@login_required
def display_table_objs(request,app_name,table_name):
    ids = []
    department = 0
    if request.user.is_admin:
        department = request.user.department_id
    admin_class, query_sets, filter_condtions, orderby_key = obj(request, app_name, table_name,ids,department)
    return render(request, 'project/project_objs.html', {'admin_class': admin_class,
                                                         'query_sets': query_sets,
                                                         'filter_condtions': filter_condtions,
                                                         'orderby_key': orderby_key,
                                                         'precious_orderby': request.GET.get("o", ''),
                                                         'search_text': request.GET.get('_q', ''),
                                                         'table_name':table_name})
@login_required
def table_objs_change(request,app_name,table_name,id):
    admin_class = king_ad.enabled_admins[app_name][table_name]
    model_form_class = create_model_form(request,admin_class)
    obj = admin_class.model.objects.get(id=id)

    if request.method == "POST":
        form_obj = model_form_class(request.POST,instance=obj)
        csrf = us.Csrf.objects.get(session=request.session.session_key)
        if csrf.csrf != request.POST.get('csrfmiddlewaretoken'):
            csrf.csrf = request.POST.get('csrfmiddlewaretoken')
            csrf.save()
            if form_obj.is_valid():
                form_obj.save()
                if table_name == 'department':
                    return redirect(reverse('department_user'))
                return redirect(reverse('table_objs',kwargs={'app_name': app_name,'table_name':table_name}))
    else:
        form_obj = model_form_class(instance=obj)
    return render(request,'king_ad/table_obj_change.html',{'model_form':form_obj,'admin_class':admin_class,
                                                           'app_name':app_name,'table_name':table_name})

@login_required
def table_obj_add(request,app_name,table_name):
    admin_class = king_ad.enabled_admins[app_name][table_name]
    model_form_class = create_model_form(request, admin_class)

    if request.method == "POST":
        csrf = us.Csrf.objects.get(session=request.session.session_key)
        if csrf.csrf != request.POST.get('csrfmiddlewaretoken'):
            csrf.csrf = request.POST.get('csrfmiddlewaretoken')
            csrf.save()
            if table_name == "tasktype" and request.POST.get('department') == "all":
                departments = us.Department.objects.all()
                for department in departments:
                    project.TaskType.objects.create(name=request.POST.get('name'),
                                                    description=request.POST.get('description'),
                                                    department=department)
                return redirect(request.path.replace('/add/', "/"))
            else:
                form_obj = model_form_class(request.POST)
                if form_obj.is_valid():
                    form_obj.save()
                    if table_name == 'department':
                        return redirect(reverse('department_user'))
                    return redirect(request.path.replace('/add/',"/"))
    else:
        form_obj = model_form_class()
    return render(request, 'king_ad/table_obj_add.html', {'model_form': form_obj,'admin_class':admin_class,
                                                          'app_name':app_name,'table_name':table_name})

@login_required
def table_obj_delete(request,app_name,table_name,id):
    admin_class = king_ad.enabled_admins[app_name][table_name]

    obj = admin_class.model.objects.get(id=id)
    if admin_class.readonly_table:
        errors = {"readonly_table": "table is readonly ,obj [%s] cannot be deleted" % obj}
    else:
        errors = {}
    if request.method == "POST":
        if not admin_class.readonly_table:
            obj.delete()
            return redirect("/admin/%s/%s/" %(app_name,table_name))

    return render(request,'king_ad/table_obj_delete.html',{'obj':obj,
                                                              'admin_class':admin_class,
                                                              'app_name': app_name,
                                                              'table_name': table_name,
                                                              'errors':errors
                                                              })

templates/king_ad/table_index.html
{% extends "base.html" %}
{% load tags %}
{% block container %}

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Table footable</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item">pages</li>
                <li class="breadcrumb-item active">Table footable</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10">
                <i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Contact Emplyee list</h4>
                        <h6 class="card-subtitle"></h6>
                        <div class="table-responsive">
                            <div id="add-contact" class="modal fade in" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                ×
                                            </button>
                                            <h4 class="modal-title" id="myModalLabel">Add New Contact</h4></div>
                                        <div class="modal-body">
                                            <from class="form-horizontal form-material">
                                                <div class="form-group">
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control" placeholder="Type name">
                                                    </div>
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control" placeholder="Email">
                                                    </div>
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control" placeholder="Phone">
                                                    </div>
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control"
                                                               placeholder="Designation"></div>
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control" placeholder="Age"></div>
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control"
                                                               placeholder="Date of joining"></div>
                                                    <div class="col-md-12 m-b-20">
                                                        <input type="text" class="form-control" placeholder="Salary">
                                                    </div>
                                                    <div class="col-md-12 m-b-20">
                                                        <div class="fileupload btn btn-danger btn-rounded waves-effect waves-light">
                                                            <span><i
                                                                    class="ion-upload m-r-5"></i>Upload Contact Image</span>
                                                            <input type="file" class="upload"></div>
                                                    </div>
                                                </div>
                                            </from>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-info waves-effect"
                                                    data-dismiss="modal">Save
                                            </button>
                                            <button type="button" class="btn btn-default waves-effect"
                                                    data-dismiss="modal">Cancel
                                            </button>
                                        </div>
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <table id="demo-foo-addrow"
                                   class="table m-t-30 table-hover contact-list footable-loaded footable"
                                   data-page-size="10">
                                {% for app_name,app_tables in table_list.items %}
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th>{{ app_name }}</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for table_name,admin in app_tables.items %}
                                            <tr>
                                                <td>
                                                    <a href="{% url 'table_objs' app_name table_name %}">{% get_model_name admin %}</a>
                                                </td>
                                                <td><a href="{% url 'table_obj_add' app_name table_name %}">add</a></td>
                                                <td>change</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
    </div>
{% endblock %}

templates/king_ad/table_obj_add.html
{% extends "king_ad/table_obj_change.html" %}

templates/king_ad/table_obj_change.html
{% extends "index.html" %}
{% load tags %}
{% block extra-css %}
    <style type="text/css">
        .filter-select-box {
            height: 200px !important;
            width: 100%;
        }

        .form-group i {
            font-size: 34px;
            vertical-align: middle;
            margin-left: 10px;
        }
    </style>
{% endblock %}
{% block wrapper %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">{% get_model_name admin_class %}</h3>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body" style="padding:3.2rem;">
                        <form class="form-horizontal" method="POST" onsubmit="upform()" style="margin-bottom: 0">
                            <div class="form-body">
                                {% csrf_token %}
                                {{ model_form.errors }}

                                {% for field in model_form %}
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group ">
                                                <label>
                                                    {% if field.field.required %}
                                                        {{ field.label }}
                                                    {% else %}
                                                        {{ field.label }}
                                                    {% endif %}
                                                </label>

                                                {% if field.name in admin_class.filter_horizontal %}
                                                    <div class="col-md-6">
                                                        {% get_m2m_obj_list admin_class.model field as m2m_obj_listt %}
                                                        {{ m2m_obj_listt }}
                                                        {% get_m2m_selected_obj_list model_form field as selected_obj_list %}
                                                        <select multiple class="filter-select-box"
                                                                id="id_{{ field.name }}_from">
                                                            {% for obj in m2m_obj_listt %}
                                                                {% if obj not in selected_obj_list %}
                                                                    <option ondblclick="MoveElementTo(this,id_{{ field.name }}_from,id_{{ field.name }}_to)"
                                                                            value="{{ obj.id }}">{{ obj }}</option>
                                                                {% endif %}
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                    <div class="col-md-1">
                                                    </div>
                                                    <div class="col-md-6">
                                                        <select multiple class="filter-select-box"
                                                                id="id_{{ field.name }}_to"
                                                                name="{{ field.name }}" tag="chosen_list">
                                                            {% for obj in selected_obj_list %}
                                                                <option ondblclick="id_{{ field.name }}_from"
                                                                        value="{{ obj.id }}">{{ obj }}</option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                {% else %}
                                                    {{ field }}
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group row">
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <div class="form-actions">
                                    <button type="submit" class="btn btn-success">保存
                                    </button>
                                    <button type="button" class="btn btn-inverse"
                                            onclick="window.location.href='{% url 'table_objs' app_name table_name %}'">
                                        返回
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        if ('{{ table_name }}' == 'tasktype') {
            $('#id_department').append("<option value='all'>所有部门</option>")
        }
        $('select').children('option[value=""]').text("请选择");
        $('input').addClass('form-control');
        $('select').addClass('form-control');
        $('textarea').addClass('form-control');
        $('textarea').attr('rows', '4');

        function MoveElementTo(ele, target_id, new_target_id) {
            var opt_ele = "<option ondblclick='MoveElementTo(ele,'" + new_target_id + "','" + target_id + "')' value='" + $(ele).val + "'>" + $(ele).text() + "</option>";
            $("#" + new_target_id).append(opt_ele);
            $(ele).remove();
        }

        function SelectAllChosenDate() {
            $("select[tag='chosen_list'] option").each(function () {
                $(this).prop("selected", true)
            });
            return true
        }

    </script>
{% endblock %}

templates/king_ad/table_obj_delete.html
{{% extends "king_ad/table_objs.html" %}
{% load tags %}
{% block content %}

    {% display_obj_related objs  %}

    <ul style="color: red">
    {% for k,v in errors.items %}
        <li>{{ k }}:{{ v }}</li>
    {% endfor %}
    </ul>
    <form method="post">{% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Yes,I'm sure">
        <input type="hidden" value="yes" name="delete_confirm">
        <input type="hidden" value="{{ selected_ids }}" name="selected_ids">
        <input type="hidden" value="{{ action }}" name="action">
        <a class="btn btn-info" href="{% url 'table_objs' app_name table_name  %}">No,Take me back</a>
    </form>


{% endblock %}


