king_ad/urls.py


from django.urls import path
from king_ad import views

urlpatterns = [
    path(r'list',views.index,name="table_index"),
    path(r'<app_name>/<table_name>/',views.display_table_objs,name="table_objs"),
    path(r'<app_name>/<table_name>/<id>/change/', views.table_objs_change, name="table_obj_change"),
    path(r'<app_name>/<table_name>/<id>/delete/', views.table_obj_delete, name="obj_delete"),
    path(r'<app_name>/<table_name>/add/',views.table_obj_add,name="table_obj_add"),
]

project/urls.py
from django.urls import path
from project import views

urlpatterns = [
    path(r'project/', views.project_obj, name='project'),
    path(r'project/index', views.project_index, name='project_index'),
    path(r'project/<int:id>', views.project_show, name='project_show'),
    path(r'project/add/<type>', views.project_add, name='project_add'),
    path(r'project/<int:id>/change/', views.project_edit, name='project_change'),
    path(r'project/api/', views.project_api),
    path(r'task/', views.task_obj, name='task'),
    path(r'task/index/', views.task_index, name='task_index'),
    path(r'task/<int:id>/', views.task_show, name='task_show'),
    path(r'task/add/', views.task_add, name='task_add'),
    path(r'task/<int:id>/change/', views.task_edit, name='task_edit'),
    path(r'projectflow/add/', views.flow_add, name='flow_add'),
    path(r'projectflow/<id>/change/', views.flow_edit, name='flow_change'),
    path(r'projectflow/', views.flow_index, name='flow'),
    path(r'examine/', views.examine_obj, name='examine'),
    path(r'examine/<int:id>/change/', views.examine_edit, name='examine_change'),
    path(r'delay/', views.delay_obj, name='delay'),
    path(r'delay/<int:id>/change/', views.delay_edit, name='delay_change'),
    # path(r'delete/api/',views.delete_api),
    path(r'upload/api/', views.upload),
    path(r'task_status/api/', views.task_status),
    path(r'contribution/', views.contribution_obj, name='contribution'),
    path(r'contribution/add/', views.contribution_add, name='contribution_add'),
    path(r'contribution/<int:id>/', views.contribution_show, name='contribution_show'),
    path(r'contribution/<int:id>/change/', views.contribution_edit, name='contribution_edit'),
    path(r'notice/', views.notice, name='notice'),
    path(r'notice/new/', views.new_notice),
    path(r'file/project/', views.file_project, name='file_project'),
    path(r'file/', views.file_obj, name='file'),
    path(r'delay/api/', views.delay_add),
    path(r'node/api/', views.project_node_file, name='node_file'),
    path(r'image/api/', views.image, name='node_file'),
]

redmine2/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from redmine2 import views as redmine
from user import views as user
from django.views.static import serve
from django.conf import settings
from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'static/<path>.*', serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}, name='upload'),
    path(r'king_ad/', include('king_ad.urls')),
    path(r'login/', user.login, name='login'),
    path(r'logout/', user.logout),
    path(r'', redmine.index, name='index'),
    path(r'<int:id>/change/', views.project_edit),
    path(r'<int:id>/', views.project_show),
    path(r'project/', include('project.urls')),
    path(r'auth/user/', user.user_obj, name='auth_user'),
    path(r'role/', user.role_obj, name='role'),
    path(r'role/add/', user.role_add, name='user_add'),
    path(r'role/<int:id>/change/', user.role_permission),
    path(r'personal/', user.personal, ),
    path(r'active/api/', user.active),
    path(r'auth/user/add/', user.user_add, name='auth_user_add'),
    path(r'auth/user/<int:id>/change/', user.user_edit, name='auth_user_change'),
    path(r'department/', user.depertment, name='department_user'),
    path(r'department/add/', user.department_add, name='department_add'),
    path(r'department/admin/', user.department_admin),
    path(r'department/<int:id>/change/', user.department_edit, name='department_edit'),
    # path(r'echo/', redmine.echo),
    path(r'400/', redmine.error_400),
    path(r'403/', redmine.error_403),
    path(r'404/', redmine.error_404),
    path(r'500/', redmine.error_500),
    path(r'503/', redmine.error_503), ]
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = redmine.error_404
handler500 = redmine.error_500

project/models.py
from django.db import models
from user.models import User, Department


# Create your models here.
class File(models.Model):
    project = models.ForeignKey('Project', on_delete=models.CASCADE, null=True, blank=True)
    task = models.ForeignKey('Task', on_delete=models.CASCADE, null=True, blank=True)
    task_discuss = models.ForeignKey('TaskDiscuss', on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    file = models.FileField(upload_to='file/%Y/%m/%d/')
    postfix = models.CharField(max_length=20, null=True, blank=True)
    existent = models.BooleanField(default=False)
    created_user = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.NullBooleanField()
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    project_discuss = models.ForeignKey('ProjectDiscuss', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "文件管理"
        verbose_name_plural = "文件管理"


class ProjectType(models.Model):
    '''项目类型'''
    name = models.CharField(max_length=30, unique=True, verbose_name='名称')
    description = models.TextField(max_length=100, verbose_name='描述')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name='所属部门')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "项目类型"
        verbose_name_plural = "项目类型"


class ProjectFlow(models.Model):
    '''项目流程'''
    flow_name = models.CharField(max_length=30, unique=True, verbose_name="名称")
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name="所属部门")
    flow_description = models.TextField(max_length=200, verbose_name="描述")
    is_active = models.BooleanField(default=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.flow_name

    class Meta:
        verbose_name = "项目流程"
        verbose_name_plural = "项目流程"


class FlowNode(models.Model):
    '''流程节点'''
    node_name = models.CharField(max_length=30)
    flow = models.ForeignKey(ProjectFlow, on_delete=models.CASCADE)
    num = models.SmallIntegerField()
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.node_name

    class Meta:
        verbose_name = "流程节点"
        verbose_name_plural = "流程节点"


class NodeNode(models.Model):
    '''流程小节点'''
    name = models.CharField(max_length=30)
    flow = models.ForeignKey(FlowNode, on_delete=models.CASCADE)
    num = models.SmallIntegerField()
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "流程小节点"
        verbose_name_plural = "流程小节点"


class Project(models.Model):
    '''项目'''
    project_name = models.CharField(max_length=30, unique=True)
    contract_no = models.CharField(null=True, blank=True, max_length=30)
    priject_description = models.TextField(max_length=200)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    tag_choice = (
        (0, "内部"),
        (1, "外部"),
    )
    tag = models.SmallIntegerField(choices=tag_choice)
    project_type = models.ForeignKey(ProjectType, on_delete=models.CASCADE)
    created_user = models.ForeignKey(User, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    examined_choice = (
        (0, "部门经理审批"),
        (1, "管理员审批"),
        (2, "审批完成"),
        (3, "审核失败"),
    )
    examined = models.SmallIntegerField(choices=examined_choice)
    node = models.ForeignKey(FlowNode, on_delete=models.CASCADE)
    flow = models.ForeignKey(ProjectFlow, on_delete=models.CASCADE)
    status_choice = (
        (0, "审核中"),
        (1, "执行中"),
        (2, "已延期"),
        (3, "已结束"),
        (4, "已搁置"),
        (5, "已暂停"),
    )
    status = models.SmallIntegerField(choices=status_choice)
    delay_choice = (
        (0, "未申请"),
        (1, "待审核"),
        (2, "审核成功"),
        (3, "审核失败"),
    )
    delay_status = models.SmallIntegerField(choices=delay_choice)
    node_node = models.ForeignKey(NodeNode, on_delete=models.CASCADE, null=True, blank=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    alert_time = models.DateTimeField(null=True, blank=True)
    supension_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.project_name

    class Meta:
        verbose_name = "项目"
        verbose_name_plural = "项目"


class ProjectFile(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)


class ProjectLog(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField()
    file = models.ForeignKey(File, on_delete=models.CASCADE, null=True, blank=True)
    created_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)


class ProjectRecord(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    record = models.TextField()
    time = models.DateField()
    created_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)


class Examine(models.Model):
    '''项目审核'''
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_user')
    examined_choice = (
        (0, "部门经理审批"),
        (1, "管理员审批"),
    )
    examine = models.SmallIntegerField(choices=examined_choice)
    is_pass = models.NullBooleanField()
    examine_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='examine_user', null=True, blank=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "项目审核"
        verbose_name_plural = "项目审核"


class ProjectNode(models.Model):
    '''项目节点'''
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    time = models.DateTimeField()
    number = models.BigIntegerField()
    unit = models.CharField(max_length=20)
    name = models.CharField(max_length=20)
    active = models.NullBooleanField()
    order = models.BigIntegerField(null=True, blank=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    node = models.ForeignKey(FlowNode, on_delete=models.CASCADE, null=True, blank=True)
    node_node = models.ForeignKey(NodeNode, on_delete=models.CASCADE, null=True, blank=True)
    node_alert_time = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "项目节点"
        verbose_name_plural = "项目节点"


class ProjectNodeFile(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    project_node = models.ForeignKey(ProjectNode, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)


class ProjectUser(models.Model):
    '''项目成员'''
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_host = models.BooleanField(default=False)
    active = models.NullBooleanField()
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "项目成员"
        verbose_name_plural = "项目成员"


class ProjectDiscuss(models.Model):
    '''任务讨论'''
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    discuss = models.TextField()
    order = models.BigIntegerField()
    active = models.NullBooleanField()
    created_user = models.ForeignKey(User, on_delete=models.CASCADE)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)


class ProjectDiscussFile(models.Model):
    project_discuss = models.ForeignKey(ProjectDiscuss, on_delete=models.CASCADE)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,Permission,Group
# Create your models here.

class Role(models.Model):
    name = models.CharField(max_length=30,unique=True)
    permission = models.ManyToManyField(Permission)
    active = models.BooleanField(default=True)
    spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "角色"
        verbose_name_plural = "角色"

class Department(models.Model):
    '''部门'''
    department_name = models.CharField(max_length=30, unique=True, verbose_name='名称')
    # active = models.BooleanField(default=True)
    # spare = models.CharField(max_length=100, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.department_name

    class Meta:
        verbose_name = "部门"
        verbose_name_plural = "部门"

class User(AbstractUser):
    phone = models.CharField(unique=True,max_length=20)
    head = models.ImageField(upload_to="image/user/%Y/%m/%d/",default="image/user/mo.jpg")
    gender_choice = (
        (0, "男"),
        (1, "女"),
    )
    gender = models.SmallIntegerField(choices=gender_choice,default=0)
    entry_time = models.DateField(null=True, blank=True)
    duty = models.CharField(max_length=20, null=True, blank=True)
    department = models.ForeignKey(Department,on_delete=models.CASCADE, null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    first_type = models.CharField(max_length=100, null=True, blank=True)
    two_type = models.CharField(max_length=100, null=True, blank=True)
    three_type = models.CharField(max_length=100, null=True, blank=True)
    four_type = models.CharField(max_length=100, null=True, blank=True)
    role = models.ForeignKey(Role,on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.first_name

    class Meta(AbstractUser.Meta):
        unique_together = ('email',)

class SessionUser(models.Model):
    session = models.CharField(max_length=100,unique=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)


class Csrf(models.Model):
    session = models.CharField(max_length=100, unique=True)
    csrf = models.CharField(max_length=100)

templates/project/contribution_show.html
{% extends "index.html" %}
{% block wrapper %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">{{ contribution.name }}</h3>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body" style="padding:3.2rem;">
                        <div class="card-body">
                            <h3 class="card-title m-b-0" style="text-align: center">{{ contribution.name }}</h3>
                        </div>
                        <div>
                            <p style="text-align: center">
                                <small class="text-muted">{{ contribution.created_user }}于{{ contribution.created_time }}创建</small>
                            </p>
                            <hr class="m-t-0">
                        </div>
                        <div class="card-body">
                            {% autoescape off %}
                                {{ contribution.description }}
                            {% endautoescape %}
                        </div>
                        <div class="form-actions">
                            <button type="button" class="btn btn-inverse"
                                    onclick="window.location.href='{% url "contribution" %}'">
                                返回
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/project/department.html
{% extends "index.html" %}
{% load tags %}
{% load static %}
{% block extra-css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/jj/iconfont.css' %}">
    <style>
        .table thead th {
            font-weight: bold;
        }

        .table tbody tr:nth-child(even) {
            background: #f2f4f8;
        }

        .contact-page-aside > .sidebar-nav > ul > li.active > a {
            border-left: 0px;
        }

        .contact-page-aside > .sidebar-nav > ul > li > a i {
            width: 12px;
            font-size: 12px;
        }

        .contact-page-aside .sidebar-nav ul li a {
            padding: 13px 35px 4px 40px;
        }
    </style>

{% endblock %}
{% block wrapper %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">部门列表</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'index' %}">首页</a></li>
                <li class="breadcrumb-item">部门</li>
                <li class="breadcrumb-item">部门列表</li>
            </ol>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- .left-right-aside-column-->
                    <div class="contact-page-aside" style="min-height: 700px">
                        <!-- .left-aside-column-->
                        <div class="left-aside bg-light-part sidebar-nav active">
                            <ul class="list-style-none">
                                {% for i in count %}
                                    {% if i.id %}
                                        <li style="position: relative"><a href="?department={{ i.id }}">{{ i.name }}
                                            <span>{{ i.count }}</span></a>
                                            <a style="position: absolute;left: 17px;top: 17px;padding: 0"
                                               href="{% url 'table_obj_change' 'user' 'department' i.id %}">
                                                <i class="iconfont icon-bianji text-info"></i></a>
                                        </li>
                                    {% else %}
                                        <li><a href="?department={{ i.id }}"
                                               style="padding: 26px 35px 10px 40px;font-weight: bold;">{{ i.name }}<span>{{ i.count }}</span></a>
                                        </li>
                                        <li class="divider" style="margin: 12px 20px"></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- /.left-aside-column-->
                        <div class="right-aside ">
                            <div class="right-page-header">
                                <div class="d-flex">
                                    <div class="align-self-center">
                                        <h4 class="card-title m-t-10">部门 / 成员 </h4></div>
                                    <div class="ml-auto">
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <div class="dataTables_wrapper" id="example23_wrapper">
                                        <table id="demo-foo-addrow"
                                               class="table m-t-30 table-hover no-wrap contact-list"
                                               data-page-size="10">
                                            <thead>
                                            <tr class="footable-sortable">
                                                {% if user.is_superuser %}
                                                    <th>经理</th>
                                                {% endif %}
                                                <th>中文名</th>
                                                <th>英文名</th>
                                                <th>手机号</th>
                                                <th>企业邮箱</th>
                                                <th>入职时间</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for obj in query_sets %}
                                                <tr>
                                                    {% if user.is_superuser %}
                                                        <td>
                                                            {% if obj.is_admin %}
                                                                <input type="checkbox" id="is_admin_{{ obj.id }}"
                                                                       name="is_admin"
                                                                       checked onchange="addadmin(this)"> <label
                                                                    for="is_admin_{{ obj.id }}"></label>
                                                            {% else %}
                                                                <input type="checkbox" id="is_admin_{{ obj.id }}"
                                                                       name="is_admin" onchange="addadmin(this)"> <label
                                                                    for="is_admin_{{ obj.id }}"></label>
                                                            {% endif %}
                                                        </td>
                                                    {% endif %}
                                                    <td>{{ obj.first_name }}</td>
                                                    <td>{{ obj.last_name }}</td>
                                                    <td>{{ obj.phone }}</td>
                                                    <td>{{ obj.email }}</td>
                                                    <td>{{ obj.entry_time|date:"Y/m/d" }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                        <div class="dataTables_info" id="example23_info" role="status"
                                             aria-live="polite"
                                             style="font-weight: 400">
                                            总计：{{ query_sets.paginator.count }}条
                                        </div>
                                        <div class="dataTables_paginate paging_simple_numbers" id="example23_paginate"
                                             style="margin-right: 48px;margin-bottom: 26px;">
                                            {% build_paginators query_sets filter_condtions precious_orderby search_text request %}
                                        </div>
                                    </div>
                                </div>
                                <!-- .left-aside-column-->
                            </div>
                            <!-- /.left-right-aside-column-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            function getUrlParam(name) {
                var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
                var r = window.location.search.substr(1).match(reg); //匹配目标参数
                if (r != null) return unescape(r[2]);
                return null; //返回参数值
            }

            var path = getUrlParam('department');
            if (path) {
                $('a[href="?department=' + path + '"]').parent().addClass('active');
            } else {
                $('a[href="?department="]').parent().addClass('active');
            }


            function addadmin(obj) {
                var is_admin;
                if ($(obj).is(':checked'))
                    is_admin = 1;
                else
                    is_admin = 0;
                $.ajax({
                    url: "/department/admin/",
                    type: "POST",
                    data: {
                        "id": $(obj).attr('id').replace(/[^0-9]/ig, ""),
                        "is_admin": is_admin
                    },
                    success: function (data) {
                    }
                });
            }

            function edit() {
                $.ajax({
                    type: "POST",   //提交的方法
                    url: "/department/{{ departments.id }}/change/", //提交的地址
                    data: {
                        "name": $('#id_department_name').val(),
                    },
                    async: false,
                    error: function (request) {  //失败的话
                        alert(request);
                    },
                    success: function (data) {  //成功
                        $('#exampleModal').modal('hide');
                        location.reload()
                    }
                });
            }
        </script>
{% endblock %}

templates/project/department_edit.html
{% extends "index.html" %}
{% load tags %}
{% block extra-css %}
    <style type="text/css">
        .form-group i {
            font-size: 34px;
            vertical-align: middle;
            margin-left: 10px;
        }
    </style>
{% endblock %}
{% block wrapper %}
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">新建部门</h3>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body" style="padding:3.2rem;">
                        <form class="form-horizontal" method="POST"
                              enctype="multipart/form-data" style="margin-bottom: 0">
                            {% csrf_token %}
                            {{ errors }}
                            <div class="form-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group ">
                                            <label >部门名称</label>
                                                {{ department_form.department_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group row">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions">
                                    <button type="submit" class="btn btn-success">保存
                                    </button>
                                    <button type="button" class="btn btn-inverse" onclick="javascript:history.back();">
                                        返回
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    $('input').addClass('form-control');
    </script>
{% endblock %}